BucketListServer/BucketListServer/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url(r'^bucketList/', include(('bucketList.urls', 'bucketList'), namespace='bucketList')),
    url(r'^tripIdeas/', include(('tripIdeas.urls', 'tripIdeas'), namespace='tripIdeas')),
    url(r'^index/', include(('indexApp.urls', 'indexApp'), namespace='index')),
    path('admin/', admin.site.urls),
]

BucketListServer/bucketList/urls.py
from django.conf.urls import url

from . import views

appName = 'bucketList'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^item/(?P<pk>\d+)/$', views.item_detail, name='item_detail'),
    url(r'^new/$', views.new_item, name='new_item'),
    url(r'^categories/$', views.categories, name='categories'),
    url(r'^last_changes/$', views.last_changes, name='last_changes'),
    url(r'^random_item/(?P<category>.+)/$', views.random_item, name='random_item'),
    url(r'^item/(?P<pk>[0-9]+)/edit/$', views.item_edit, name='item_edit'),
    url(r'^item/(?P<pk>[0-9]+)/delete/$', views.item_delete, name='item_delete'),
    url(r'^search/$', views.search_item, name='search_item'),
    url(r'^item_to_come/$', views.item_to_come, name='item_to_come'),
    url(r'^rename_category/$', views.rename_category, name='rename_category'),
]

BucketListServer/indexApp/urls.py
from django.conf.urls import url

from . import views

appName = 'indexApp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

BucketListServer/bucketList/models.py
from django.db import models
from django import forms
from django.utils import timezone

class Item(models.Model):
    name = models.CharField("Nom", max_length=300)
    created_date_time = models.DateTimeField("Date de création", default=timezone.now)
    modified_date_time = models.DateTimeField("Date de modofication", default=timezone.now)
    category = models.CharField("Catégorie", max_length=80, default="Catégorie par défaut")
    is_done = models.BooleanField("Check", default=False)
    time_window_start = models.DateField("Début de l'événement", default=None, null=True, blank=True)
    time_window_end = models.DateField("Fin de l'événement", default=None, null=True, blank=True)
    CREATOR_CHOICES = (
        ('MAG', 'Marco-polo'),
        ('SAM', 'Samo-polo')
    )
    creator = models.TextField("Créateur", max_length=3, choices=CREATOR_CHOICES, null=True)

    def __str__(self):
        if len(self.name) > 40:
            return str(self.name)[:40] + '... (' + str(self.modified_date_time) + ')'
        else:
            return str(self.name) + ' (' + str(self.modified_date_time) + ')'


class DateInput(forms.DateInput):
    input_type = 'date'


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'category', 'is_done', 'time_window_start', 'time_window_end', 'creator']
        widgets = {
            'name': forms.Textarea(attrs={'cols': 70, 'rows': 2}),
            'time_window_start': DateInput(),
            'time_window_end': DateInput()
        }

BucketListServer/bucketList/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

import random

from .models import Item, ItemForm

bgs = [
    '26733413434_815fcea204_k.jpg',
    'daniel-von-appen-255535-unsplash.jpg',
    'ethan-elisara-505545-unsplash.jpg',
    'joshua-earle-682748-unsplash.jpg',
    'joseph-barrientos-20264-unsplash.jpg',
    'joschko-hammermann-2224-unsplash.jpg',
    'conner-murphy-345177-unsplash.jpg',
    'brooklyn-morgan-390-unsplash.jpg',
    'lachlan-dempsey-344426-unsplash.jpg',
    'scott-webb-51542-unsplash.jpg',
    'elizeu-dias-520684-unsplash.jpg',
    'leio-mclaren-leiomclaren-302950-unsplash.jpg',
    'kees-streefkerk-352781-unsplash.jpg'
]
session_BG = bgs[random.randint(0, len(bgs))-1]
bg_last_update = timezone.now()

def get_new_bg():
    global bgs
    global session_BG
    global bg_last_update
    if (timezone.now() - bg_last_update).total_seconds() > 3600:
        session_BG = bgs[random.randint(0, len(bgs))-1]
        bg_last_update = timezone.now()


# ============================================ List Requests ============================================ #

def index(request):
    get_new_bg()
    categories = Item.objects.values_list('category', flat=True).distinct()
    ordered_items = []
    for category in categories:
        ordered_items.append({'category': category,
                              'items': list(Item.objects.filter(category=category)[:5])})

    last_modified_mag = Item.objects.filter(creator='MAG').order_by('-created_date_time')[:5]
    last_modified_sam = Item.objects.filter(creator='SAM').order_by('-created_date_time')[:5]
    return render(request, 'bucketList/index.html',
                  {
                      'ordered_items': ordered_items[:5],
                      'last_modified_mag': last_modified_mag,
                      'last_modified_sam': last_modified_sam,
                      'bg': session_BG
                  })


def categories(request):
    get_new_bg()
    categories = Item.objects.values_list('category', flat=True).distinct()
    ordered_items = []
    for category in categories:
        ordered_items.append({'category': category,
                              'items': list(Item.objects.filter(category=category))})
    return render(request, 'bucketList/categories_list.html', {'ordered_items': ordered_items, 'bg': session_BG})


def rename_category(request):
    if 'old_category_name' in request.POST and 'new_category_name' in request.POST and request.POST['old_category_name'] and request.POST['new_category_name']:
        old_name = request.POST['old_category_name']
        new_name = request.POST['new_category_name']
        Item.objects.filter(category=old_name).update(category=new_name)
    return redirect('bucketList:categories')


def last_changes(request):
    get_new_bg()
    last_modified_mag = Item.objects.filter(creator='MAG').order_by('-modified_date_time')[:15]
    last_modified_sam = Item.objects.filter(creator='SAM').order_by('-modified_date_time')[:15]
    return render(request, 'bucketList/last_changes.html',
                  {
                      'last_modified_mag': last_modified_mag,
                      'last_modified_sam': last_modified_sam,
                      'bg': session_BG
                  })


def random_item(request, category):
    get_new_bg()
    items = list(Item.objects.filter(category=category))
    no_time_window = None
    item = None
    while (True):
        item = items[random.randint(0, len(items))-1]
        no_time_window = item.time_window_start == None or item.time_window_end == None
        if (no_time_window or (item.time_window_start <= timezone.now().date() and item.time_window_end >= timezone.now().date())):
            break

    return render(request, 'bucketList/item_detail.html', {'item': item, 'bg': session_BG, 'now': timezone.now().date(), 'start': item.time_window_start, 'end': item.time_window_end, 'random': True})


def search_item(request):
    get_new_bg()
    if 'search_value' in request.POST and request.POST['search_value']:
        search_value = request.POST['search_value']
        items = Item.objects.filter(name__icontains=search_value)
    else:
        items = []
    return render(request, 'bucketList/search_result.html',
                  {
                      'search_result': items,
                      'bg': session_BG
                  })


def item_to_come(request):
    get_new_bg()
    items = Item.objects.filter(time_window_end__gte=timezone.now().date()).order_by('time_window_end')
    return render(request, 'bucketList/item_to_come.html',
                  {
                      'search_result': items,
                      'bg': session_BG
                  })


# ============================================ Item Requests ============================================ #

def new_item(request):
    get_new_bg()
    categories = Item.objects.values_list('category', flat=True).distinct()
    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            item = form.save()
            return redirect('bucketList:item_detail', pk=item.pk)
    else:
        form = ItemForm()
    return render(request, 'bucketList/item_edit.html', {'form': form,
                                                         'categories': categories,
                                                         'new': True,
                                                         'bg': session_BG})


def item_edit(request, pk):
    get_new_bg()
    item = get_object_or_404(Item, pk=pk)
    categories = Item.objects.values_list('category', flat=True).distinct()
    if request.method == "POST":
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            item = form.save(commit=False)
            item.modified_date_time = timezone.now()
            item.save()
            return redirect('bucketList:item_detail', pk=item.pk)
    else:
        form = ItemForm(instance=item)
    return render(request, 'bucketList/item_edit.html', {'form': form,
                                                         'categories': categories,
                                                         'new': False,
                                                         'bg': session_BG})


def item_delete(request, pk):
    item = get_object_or_404(Item, pk=pk)
    item.delete()
    return redirect('bucketList:index')


def item_detail(request, pk):
    get_new_bg()
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'bucketList/item_detail.html', {'item': item, 'bg': session_BG, 'now': timezone.now().date(), 'start': item.time_window_start, 'end': item.time_window_end})

BucketListServer/bucketList/templates/bucketList/categories_list.html
{% extends 'base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Bucket List - Catégories{% endblock %}

{% block content %}

<script>
function showDiv(id) {
  var elem = document.getElementById(id);
  if (elem.style.display == "none") {
    document.getElementById(id).style.display = "block";
  } else {
    document.getElementById(id).style.display = "none";
  }
  document.getElementById('old_category_name').value = id;
}
</script>

  <div class="jumbotron col-lg-10 offset-lg-1 see-through main-div">
    <form class="form-inline my-2 mb-2" action="{% url 'bucketList:rename_category' %}" method="post">
      {% csrf_token %}
      <input class="form-control mr-sm-2 border-warning" type="text" placeholder="Vieux nom" name="old_category_name" id="old_category_name" autocomplete="off" required>
      <button class="btn btn-secondary my-2 mr-sm-2 my-sm-0" type="submit"><span class="glyphicon glyphicon-arrow-right"></span></button>
      <input class="form-control mr-sm-2 border-warning" type="text" placeholder="Nouveau nom" name="new_category_name" id="new_category_name" autocomplete="off" required>
    </form>
    {% if ordered_items %}
      {% for category in ordered_items %}
        <div class="card border-info mb-3">
          <div class="card-header">
            <a class="text-info category-card-title" onclick="showDiv('{{category.category}}')">{{category.category}}</a>

            <a href="{% url 'bucketList:random_item' category=category.category %}" class="btn btn-outline-info float-right">Random</a>

          </div>
          <div class="card-body" id="{{category.category}}" style="display:none;">
            <ul>
              {% for item in category.items %}
                <li><a class="text-info" href="/bucketList/item/{{item.pk}}">{{item.name}}{% if item.is_done is True %}<span style="color: #5cb85c; margin-left:5px;" class="glyphicon glyphicon-ok-sign"></span>{% else %}<span style="color: #d9534f; margin-left:5px;" class="glyphicon glyphicon-remove-sign"></span>{% endif %}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
      {% endfor %}
    {% endif %}
  </div>

{% endblock %}

BucketListServer/bucketList/templates/bucketList/index.html
{% extends 'base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Bucket List - Accueil{% endblock %}

{% block content %}

<div class="jumbotron col-lg-10 offset-lg-1 see-through main-div">
  {% if ordered_items %}
    {% for category in ordered_items %}
      <div class="card border-info mb-3">
        <div class="card-header">{{category.category}}</div>
        <div class="card-body">
          <ul>
            {% for item in category.items %}
              <li><a class="text-info" href="/bucketList/item/{{item.pk}}">{{item.name}}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    {% endfor %}
  {% endif %}

  {% if last_modified_sam %}
  <div class="card border-info mb-3">
    <div class="card-header">Dernières modification (Sam)</div>
    <div class="card-body">
      <ul>
        {% for item in last_modified_sam %}
          <li><a class="text-info" href="/bucketList/item/{{item.pk}}">{{item.name}}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}

  {% if last_modified_mag %}
  <div class="card border-info mb-3">
    <div class="card-header">Dernières modification (Marc)</div>
    <div class="card-body">
      <ul>
        {% for item in last_modified_mag %}
          <li><a class="text-info" href="/bucketList/item/{{item.pk}}">{{item.name}}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
</div>

{% endblock %}

BucketListServer/bucketList/templates/bucketList/item_detail.html
{% extends 'base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Bucket List - Détails{% endblock %}

{% block content %}

<div class="jumbotron see-through card border-primary col-lg-10 center-div">
  {% if random is True %}<a href="." style="margin-top: 20px; margin-right: 20px; position: absolute; top: 0px; right: 0px;" class="btn btn-outline-info">Random</a>{% endif %}
  {% if item %}
    <h3 style="margin-bottom: 30px;">{{item.name}}</h4>
    <h5>Catégorie: {{item.category}}</h5>
    <h5>Date de création: {{item.created_date_time}}</h5>
    <h5>Date de modification: {{item.modified_date_time}}</h5>
    <h5>Déjà fait: {% if item.is_done is True %}<span style="color: #5cb85c;" class="glyphicon glyphicon-ok-sign"></span>{% else %}<span style="color: #d9534f" class="glyphicon glyphicon-remove-sign"></span>{% endif %}</h5>
    <h5 {% if now >= start and now <= end %}style="color: #5cb85c;"{% endif %}>Début de l'événement: {% if not item.time_window_start %}<span class="glyphicon glyphicon-remove-sign"></span>{% else %}{{item.time_window_start}}{% endif %}</h5>
    <h5 {% if now >= start and now <= end %}style="color: #5cb85c;"{% endif %}>Fin de l'événement: {% if not item.time_window_end %}<span class="glyphicon glyphicon-remove-sign"></span>{% else %}{{item.time_window_end}}{% endif %}</h5>
    <h5>Créateur: {{item.get_creator_display}}</h5>
    <div class="row">
      <a href="{% url 'bucketList:item_edit' pk=item.pk %}" style="margin-top: 30px; width: 200px; margin-right: 10px; display: inline-block;" class="btn btn-outline-warning">Éditer</a>
      <a href="{% url 'bucketList:item_delete' pk=item.pk %}" style="margin-top: 30px; margin-left: 10px; width: 200px; display: inline-block;" class="btn btn-outline-danger">Supprimer</a>
    </div>
  {% endif %}
</div>

{% endblock %}

BucketListServer/bucketList/templates/bucketList/item_edit.html
{% extends 'base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Bucket List - {% if new is True %}Nouveau{% else %}Modification{% endif %}{% endblock %}

{% block content %}

<script>
function fillCategoryInForm(category) {
  var elem = document.getElementById('id_category');
  elem.value = category;
}

</script>

<div class="jumbotron col-lg-10 offset-lg-1 see-through main-div card border-primary new-item-form">
  <h1 class="col-lg-12 new-title">{% if new is True %}Nouvelle {% else %}Modification d'{% endif %}idée</h1>
  <div class="row">

    <div class="form-group col-lg-6 offset-lg-3">
      <form method="POST" class="custom-form">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary form-button">Sauvegarder</button>
      </form>
    </div>

    {% if categories %}
    <div class="col-lg-3">
      <h5>Catégories:</h3>
      <ul>
        {% for cat in categories %}
          <li class="category-clickable" onclick="fillCategoryInForm('{{cat}}')">{{cat}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

  </div>
</div>

{% endblock %}

BucketListServer/bucketList/templates/bucketList/item_to_come.html
{% extends 'base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Bucket List - Bientôt{% endblock %}

{% block content %}

<div class="jumbotron col-lg-10 offset-lg-1 see-through main-div">

  <div class="card border-info mb-3">
    <div class="card-header">Événement à venir</div>
    <div class="card-body">
      <ul>
        {% for item in search_result %}
          <li><a class="text-info" href="/bucketList/item/{{item.pk}}">{{item.name}} ({{item.time_window_start}} - {{item.time_window_end}})</a></li>
        {% empty %}
          <li>Aucun événements sont à venir</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

{% endblock %}

BucketListServer/bucketList/templates/bucketList/last_changes.html
{% extends 'base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Bucket List - Derniers changements{% endblock %}

{% block content %}

<script type="text/javascript">
function showDiv(id) {
  var elem = document.getElementById(id);
  if (elem.style.display == "none") {
    document.getElementById(id).style.display = "block";
  } else {
    document.getElementById(id).style.display = "none";
  }
}
</script>

  <div class="jumbotron col-lg-10 offset-lg-1 see-through main-div">
    <div class="card border-info mb-3">
      <div class="card-header">Dernières modification (Sam)</div>
      <div class="card-body">
        <ul>
          {% for activity in last_modified_sam %}
            <li><a class="text-info" href="/tripIdeas/activity/{{activity.pk}}">{{activity.name}}</a></li>
            {% empty %}
              <li>Aucune dernières modifications</li>
            {% endfor %}
        </ul>
      </div>
    </div>

    <div class="card border-info mb-3">
      <div class="card-header">Dernières modification (Marc)</div>
      <div class="card-body">
        <ul>
          {% for activity in last_modified_mag %}
            <li><a class="text-info" href="/tripIdeas/activity/{{activity.pk}}">{{activity.name}}</a></li>
          {% empty %}
            <li>Aucune dernières modifications</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  </div>

{% endblock %}

BucketListServer/bucketList/templates/bucketList/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="dropdown">
    <a class="dropbtn navbar-brand no-margin-right small-padding-sides" href="{% url 'bucketList:index' %}">BucketList</button>
      <div class="dropdown-content">
        <a class="navbar-brand no-margin-right" href="{% url 'tripIdeas:index' %}">Trip Ideas</a>
      </div>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation" style="">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <div class="dropdown">
        <a class="dropbtn nav-link">Idées <span class="glyphicon glyphicon-collapse-down"></span></button>
        <div class="dropdown-content">
          <a class="nav-link" href="{% url 'bucketList:categories' %}">Catégories</a>
          <a class="nav-link" href="{% url 'bucketList:last_changes' %}">Derniers ajouts/modifications</a>
          <a class="nav-link" href="{% url 'bucketList:item_to_come' %}">À venir</a>
          <a class="nav-link add-dropdown-item" href="{% url 'bucketList:new_item' %}">Nouveau</a>
        </div>
      </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'bucketList:search_item' %}" method="post">
      {% csrf_token %}
      <input class="form-control mr-sm-1" type="text" placeholder="Search" name="search_value" id="search_value" autocomplete="off">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit"><span class="glyphicon glyphicon-search"></span></button>
    </form>
  </div>
</nav>

BucketListServer/bucketList/templates/bucketList/search_result.html
{% extends 'base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Bucket List - Recherche{% endblock %}

{% block content %}

<div class="jumbotron col-lg-10 offset-lg-1 see-through main-div">

  <div class="card border-info mb-3">
    <div class="card-header">Résultat de la recherche</div>
    <div class="card-body">
      <ul>
        {% for item in search_result %}
          <li><a class="text-info" href="/bucketList/item/{{item.pk}}">{{item.name}}</a></li>
        {% empty %}
          <li>Aucun résultats pour cette recherche</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

{% endblock %}