BucketListServer/BucketListServer/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url(r'^bucketList/', include(('bucketList.urls', 'bucketList'), namespace='bucketList')),
    url(r'^tripIdeas/', include(('tripIdeas.urls', 'tripIdeas'), namespace='tripIdeas')),
    url(r'^index/', include(('indexApp.urls', 'indexApp'), namespace='index')),
    path('admin/', admin.site.urls),
]

BucketListServer/indexApp/urls.py
from django.conf.urls import url

from . import views

appName = 'indexApp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

BucketListServer/tripIdeas/urls.py
from django.conf.urls import url

from . import views

appName = 'tripIdeas'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^last_changes/$', views.last_changes, name='last_changes'),
    url(r'^by_country/$', views.by_country, name='by_country'),
    url(r'^by_season/$', views.by_season, name='by_season'),
    url(r'^new_activity/$', views.new_activity, name='new_activity'),
    url(r'^activity/(?P<pk>\d+)/$', views.activity_detail, name='activity_detail'),
    url(r'^activity/(?P<pk>[0-9]+)/edit/$', views.activity_edit, name='activity_edit'),
    url(r'^activity/(?P<pk>[0-9]+)/delete/$', views.activity_delete, name='activity_delete'),
    url(r'^all_trips/$', views.all_trips, name='all_trips'),
    url(r'^last_changes_trip/$', views.last_changes_trip, name='last_changes_trip'),
    url(r'^new_trip/$', views.new_trip, name='new_trip'),
    url(r'^trip/(?P<pk>\d+)/$', views.trip_detail, name='trip_detail'),
    url(r'^trip/(?P<pk>[0-9]+)/edit/$', views.trip_edit, name='trip_edit'),
    url(r'^trip/(?P<pk>[0-9]+)/delete/$', views.trip_delete, name='trip_delete'),
    url(r'^search/$', views.search_item, name='search_item'),
    url(r'^working/$', views.working_on_it, name='working_on_it'),
]

BucketListServer/tripIdeas/models.py
from django.db import models
from django import forms
from django.utils import timezone
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

class Activity(models.Model):
    CREATOR_CHOICES = (
        ('MAG', 'Marco-Polo'),
        ('SAM', 'Samo-Polo')
    )
    SEASON_CHOICES = (
        ('E', 'Été'),
        ('A', 'Automne'),
        ('H', 'Hiver'),
        ('P', 'Printemps')
    )
    title = models.CharField("Nom d'activité", max_length=100)
    country = CountryField('Pays')
    created_date_time = models.DateTimeField("Date de création", default=timezone.now)
    modified_date_time = models.DateTimeField("Date de modofication", default=timezone.now)
    creator = models.TextField("Créateur", max_length=3, choices=CREATOR_CHOICES, default='SAM')

    description = models.CharField(max_length=300, null=True, blank=True)
    link = models.CharField('lien', default='', max_length=2083, null=True, blank=True)
    season = models.TextField("Saison", max_length=1, choices=SEASON_CHOICES, null=True, blank=True)
    favorable_date = models.DateField("Date la plus favorable", default=None, null=True, blank=True)
    date_window = models.IntegerField("Plus/Moins (Jour)", default=0)
    postal_code = models.CharField("Code Postal", max_length=15, default=None, null=True, blank=True)


    def __str__(self):
        if len(self.title) > 40:
            return self.title[:40] + '... (' + str(self.country) + ')'
        return self.title + ' (' + str(self.country) + ')'


class Trip(models.Model):
    title = models.CharField("Nom du Voyage", max_length=300)
    description = models.CharField(max_length=500, null=True, blank=True)
    country_list = CountryField(multiple=True)
    created_date_time = models.DateTimeField("Date de création", default=timezone.now)
    modified_date_time = models.DateTimeField("Date de modofication", default=timezone.now)
    activities = models.ManyToManyField(Activity)
    CREATOR_CHOICES = (
        ('MAG', 'Marco-Polo'),
        ('SAM', 'Samo-Polo')
    )
    creator = models.TextField("Créateur", max_length=3, choices=CREATOR_CHOICES, null=True)

    def __str__(self):
        if len(self.title) > 40:
            return self.title[40] + '... (' + str(len(self.country_list)) + ')'
        return self.title + ' (' + str(len(self.country_list)) + ')'


class DateInput(forms.DateInput):
    input_type = 'date'


class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['title', 'description', 'link', 'country', 'creator', 'season', 'favorable_date', 'date_window', 'postal_code']
        widgets = {
            'title': forms.TextInput(attrs={'size':70, 'autocomplete': 'off'}),
            'description': forms.Textarea(attrs={'cols': 70, 'rows': 3, 'autocomplete': 'off'}),
            'link': forms.TextInput(attrs={'size':70, 'autocomplete': 'off'}),
            'country': CountrySelectWidget(),
            'favorable_date': DateInput(),
            'postal_code': forms.TextInput(attrs={'autocomplete': 'off'}),
        }


class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = ['title', 'description', 'creator']
        widgets = {
            'title': forms.TextInput(attrs={'size':70, 'autocomplete': 'off'}),
            'description': forms.Textarea(attrs={'cols': 70, 'rows': 3, 'autocomplete': 'off'})
        }

BucketListServer/tripIdeas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django_countries import countries

import random

from .models import Activity, Trip, ActivityForm, TripForm
from .google_scrapper import get_google_urls

SEASONS_DICT = {'H': 'Hiver',
                'A': 'Automne',
                'P': 'Printemps',
                'E': 'Été'}

bgs = [
    '26733413434_815fcea204_k.jpg',
    'daniel-von-appen-255535-unsplash.jpg',
    'ethan-elisara-505545-unsplash.jpg',
    'joshua-earle-682748-unsplash.jpg',
    'joseph-barrientos-20264-unsplash.jpg',
    'joschko-hammermann-2224-unsplash.jpg',
    'conner-murphy-345177-unsplash.jpg',
    'brooklyn-morgan-390-unsplash.jpg',
    'lachlan-dempsey-344426-unsplash.jpg',
    'scott-webb-51542-unsplash.jpg',
    'elizeu-dias-520684-unsplash.jpg',
    'leio-mclaren-leiomclaren-302950-unsplash.jpg',
    'kees-streefkerk-352781-unsplash.jpg'
]
session_BG = bgs[random.randint(0, len(bgs))-1]
bg_last_update = timezone.now()

def get_new_bg():
    global bgs
    global session_BG
    global bg_last_update
    if (timezone.now() - bg_last_update).total_seconds() > 3600:
        session_BG = bgs[random.randint(0, len(bgs))-1]
        bg_last_update = timezone.now()

def get_country_name_from_code(code):
    return dict(countries)[code]


# ============================================ List Requests ============================================ #

def index(request):
    get_new_bg()
    countries = Activity.objects.values_list('country', flat=True).distinct()[:5]
    ordered_activities = []
    for country in countries:
        ordered_activities.append({
            'country': get_country_name_from_code(country),
            'activities': list(Activity.objects.filter(country=country)[:5])
        })
    return render(request, 'tripIdeas/index.html', {'bg': session_BG, 'ordered_activities': ordered_activities})


def by_country(request):
    get_new_bg()
    countries = Activity.objects.values_list('country', flat=True).distinct()
    ordered_activities = []
    for country in countries:
        ordered_activities.append({
            'filter': get_country_name_from_code(country),
            'activities': list(Activity.objects.filter(country=country))
        })
    return render(request, 'tripIdeas/by_filter.html', {'bg': session_BG, 'ordered_activities': ordered_activities})


def by_season(request):
    get_new_bg()
    seasons = Activity.objects.values_list('season', flat=True).distinct()
    ordered_activities = []
    for season in seasons:
        ordered_activities.append({
            'filter': SEASONS_DICT[season],
            'activities': list(Activity.objects.filter(season=season))
        })
    return render(request, 'tripIdeas/by_filter.html', {'bg': session_BG, 'ordered_activities': ordered_activities})


def last_changes(request):
    get_new_bg()
    creator_list = {}
    mag_trips = Activity.objects.filter(creator='MAG').order_by('-modified_date_time')[:15]
    sam_trips = Activity.objects.filter(creator='SAM').order_by('-modified_date_time')[:15]

    if len(sam_trips) > 0:
        creator_list['Samo-Polo'] = sam_trips
    else:
        creator_list['Samo-Polo'] = None
    if len(mag_trips) > 0:
        creator_list['Marco-Polo'] = mag_trips
    else:
        creator_list['Marco-Polo'] = None
    if len(creator_list) == 0:
        creator_list = None

    return render(request, 'tripIdeas/last_changes.html',
                  {
                      'creator_list': creator_list,
                      'bg': session_BG
                  })


def all_trips(request):
    get_new_bg()
    creator_list = {}
    mag_trips = Trip.objects.filter(creator='MAG').order_by('title')
    sam_trips = Trip.objects.filter(creator='SAM').order_by('title')

    if len(sam_trips) > 0:
        creator_list['Samo-Polo'] = sam_trips
    else:
        creator_list['Samo-Polo'] = None
    if len(mag_trips) > 0:
        creator_list['Marco-Polo'] = mag_trips
    else:
        creator_list['Marco-Polo'] = None
    if len(creator_list) == 0:
        creator_list = None

    return render(request, 'tripIdeas/simple_trip_list.html',
                  {
                      'creator_list': creator_list,
                      'bg': session_BG
                  })


def last_changes_trip(request):
    get_new_bg()
    creator_list = {}
    mag_trips = Trip.objects.filter(creator='MAG').order_by('-modified_date_time')[:15]
    sam_trips = Trip.objects.filter(creator='SAM').order_by('-modified_date_time')[:15]

    if len(sam_trips) > 0:
        creator_list['Samo-Polo'] = sam_trips
    else:
        creator_list['Samo-Polo'] = None
    if len(mag_trips) > 0:
        creator_list['Marco-Polo'] = mag_trips
    else:
        creator_list['Marco-Polo'] = None
    if len(creator_list) == 0:
        creator_list = None

    return render(request, 'tripIdeas/simple_trip_list.html',
                  {
                    'creator_list': creator_list,
                    'bg': session_BG
                  })


def search_item(request):
    get_new_bg()
    items = {}
    if 'search_value' in request.POST and request.POST['search_value']:
        search_value = request.POST['search_value']
        activities = Activity.objects.filter(title__icontains=search_value)
        trips = Trip.objects.filter(title__icontains=search_value)
        items['activities'] = activities
        items['trips'] = trips

    return render(request, 'tripIdeas/search_result.html',
                  {
                      'search_result': items,
                      'bg': session_BG
                  })

# ============================================ Activity Requests ============================================ #

def new_activity(request):
    get_new_bg()
    if request.method == "POST":
        form = ActivityForm(request.POST)
        if form.is_valid():
            item = form.save()
            return redirect('tripIdeas:activity_detail', pk=item.pk)
    else:
        form = ActivityForm()
    return render(request, 'tripIdeas/activity_edit.html', {'form': form,
                                                             'new': True,
                                                             'bg': session_BG})



def activity_edit(request, pk):
    get_new_bg()
    activity = get_object_or_404(Activity, pk=pk)
    if request.method == "POST":
        form = ActivityForm(request.POST, instance=activity)
        if form.is_valid():
            activity = form.save(commit=False)
            activity.modified_date_time = timezone.now()
            activity.save()
            return redirect('tripIdeas:activity_detail', pk=activity.pk)
    else:
        form = ActivityForm(instance=activity)
    return render(request, 'tripIdeas/activity_edit.html', {'form': form,
                                                            'new': False,
                                                            'bg': session_BG})


def activity_delete(request, pk):
    activity = get_object_or_404(Activity, pk=pk)
    activity.delete()
    return redirect('tripIdeas:index')


def activity_detail(request, pk):
    get_new_bg()
    activity = get_object_or_404(Activity, pk=pk)
    urls = get_google_urls(activity.title)
    return render(request, 'tripIdeas/activity_detail.html', {'activity': activity,
                                                              'bg': session_BG,
                                                              'urls': urls})


# ============================================ Trip Requests ============================================ #

def new_trip(request):
    get_new_bg()
    activities = Activity.objects.all()
    if request.method == "POST":
        form = TripForm(request.POST)
        trips_activities = []
        if form.is_valid():
            if request.POST['activities_pks']:
                activities_pks = request.POST.getlist('activities_pks')
                for pk in activities_pks:
                    trips_activities.append(get_object_or_404(Activity, pk=pk))

            trip = form.save()
            trip.activities.set(trips_activities)
            trip.country_list = [a.country for a in trip.activities.all()]
            trip.save()
            return redirect('tripIdeas:trip_detail', pk=trip.pk)
    else:
        form = TripForm()
    return render(request, 'tripIdeas/trip_edit.html', {'form': form,
                                                        'activities': activities,
                                                        'new': True,
                                                        'bg': session_BG})


def trip_edit(request, pk):
    get_new_bg()
    trip = get_object_or_404(Trip, pk=pk)
    activities = Activity.objects.all()
    activities_tuple = []
    for a in activities:
        activities_tuple.append([a, (a in trip.activities.all())])

    if request.method == "POST":
        form = TripForm(request.POST, instance=trip)
        trips_activities = []
        if form.is_valid():
            if request.POST['activities_pks']:
                activities_pks = request.POST.getlist('activities_pks')
                for pk in activities_pks:
                    trips_activities.append(get_object_or_404(Activity, pk=pk))

            trip = form.save(commit=False)
            trip.activities.set(trips_activities)
            trip.country_list = [a.country for a in trip.activities.all()]
            trip.modified_date_time = timezone.now()
            trip.save()
            return redirect('tripIdeas:trip_detail', pk=trip.pk)
    else:
        form = TripForm(instance=trip)
    return render(request, 'tripIdeas/trip_edit.html', {'form': form,
                                                        'activities': activities_tuple,
                                                        'new': False,
                                                        'bg': session_BG})

def trip_delete(request, pk):
    get_new_bg()

BucketListServer/tripIdeas/templates/tripIdeas/activity_detail.html
{% extends 'tripIdeas/base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Trip Ideas - Détails activité{% endblock %}

{% block content %}

{% load static %}

<script type="text/javascript" defer>
  var slideIndex = 1;

  // Next/previous controls
  function plusSlides(n) {
    showSlides(slideIndex += n);
  }

  // Thumbnail image controls
  function currentSlide(n) {
    showSlides(slideIndex = n);
  }

  function showSlides(n) {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    if (n > slides.length) {
      slideIndex = 1
    }
    if (n < 1) {
      slideIndex = slides.length
    }
    for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex - 1].style.display = "block";
    dots[slideIndex - 1].className += " active";
  }

  function showDiv(id) {
    var elem = document.getElementById(id);
    if (elem.style.display == "none") {
      document.getElementById(id).style.display = "block";
    } else {
      document.getElementById(id).style.display = "none";
    }
  }

  function getFirstURLs(queryStr) {
    return new Promise(resolve => {
      GoogleImageSearch.searchImage(queryStr).then((res) => {
        resolve(res.splice(0, 3));
      });
    });
  }

  async function loadImages() {
    var queryStr = document.getElementById('queryStr').innerText;
    var slides = document.getElementsByClassName("mySlides");
    var urls = await getFirstURLs(queryStr);
    for (var i = 0; i < slides.length; i++) {
      slides[i].children[1].src = urls[i];
    }
  }

  function AfterLoad() {
    //loadImages();
    showSlides(slideIndex);
  }

  window.onload = AfterLoad;
</script>

<div class="jumbotron see-through card border-primary col-lg-10 trip_center_div">
  {% if activity %}
    <span style="display: none;" id="queryStr">{{activity.title}}</span>
    <h3 style="margin-bottom: 30px;">{{activity.title}}</h4>
    <h5>Description:</h5><p>{{activity.description}}</p>
    <h5>Lien: <a href="{{activity.link}}" target="_blank" rel="noopener noreferrer">{{activity.link}}</a></h5>
    <h5>Pays: {{activity.country.name}}<img class="flag-icon" src="{{activity.country.flag}}"/></h5>
    <h5>Date de création: {{activity.created_date_time}}</h5>
    <h5>Date de modification: {{activity.modified_date_time}}</h5>
    <h5>Créateur: {{activity.get_creator_display}}</h5>
    <h5>Saison: {{activity.get_season_display}}</h5>
    <div style="margin-top: 30px;">
      <a href="{% url 'tripIdeas:activity_edit' pk=activity.pk %}" style="width: 200px; margin-right: 10px; display: inline-block;" class="btn btn-outline-warning">Éditer</a>
      <a href="{% url 'tripIdeas:activity_delete' pk=activity.pk %}" style="margin-left: 10px; width: 200px; display: inline-block;" class="btn btn-outline-danger">Supprimer</a>
    </div>
    <div class="card border-info mb-3 image-slider-main-div">
      <div class="card-header">
        <a class="text-info category-card-title" onclick="showDiv('images-slider')">Images</a>
      </div>
      <div class="card-body" id="images-slider" style="display:none;">

        <div class="slideshow-container">
          {% for img_url in urls %}
            <div class="mySlides" {% if forloop.counter0 != 0 %}style="display:None"{% endif %}>
              <div class="numbertext">{{ forloop.counter }} / {{urls|length}}</div>
              <img src="{{img_url}}" style="width:100%; height: 100%;">
            </div>
          {% endfor %}
          <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
          <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>
        <br>

        <div style="text-align:center">
          <span class="dot" onclick="currentSlide(1)"></span>
          <span class="dot" onclick="currentSlide(2)"></span>
          <span class="dot" onclick="currentSlide(3)"></span>
          <span class="dot" onclick="currentSlide(4)"></span>
          <span class="dot" onclick="currentSlide(5)"></span>
        </div>
      </div>
    </div>
  {% else %}
    <h3>Aucune activité à afficher.</h3>
  {% endif %}
</div>

{% endblock %}

BucketListServer/tripIdeas/templates/tripIdeas/activity_edit.html
{% extends 'tripIdeas/base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Trip Ideas - {% if new is True %}Nouvelle {% else %}Modification d'{% endif %}activité{% endblock %}

{% block content %}

<div class="jumbotron col-lg-10 offset-lg-1 see-through main-div card border-primary new-item-form">
  <h1 class="col-lg-12 new-title">{% if new is True %}Nouvelle {% else %}Modification d'{% endif %}idée</h1>
  <div class="row">

    <div class="form-group col-lg-6 offset-lg-3">
      <form method="POST" class="custom-form">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary form-button">Sauvegarder</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

BucketListServer/tripIdeas/templates/tripIdeas/all_activities.html
{% extends 'tripIdeas/base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Trip Ideas - Toute les activités{% endblock %}

{% block content %}

  <div class="jumbotron col-lg-10 offset-lg-1 see-through main-div">
    {% if activities %}
    <ul>
      {% for activity in activities %}
        <li><a class="text-info" href="/tripIdeas/activity/{{activity.pk}}">{{activity.title}}</a></li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>

{% endblock %}

BucketListServer/tripIdeas/templates/tripIdeas/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'bucketList/favicon-16x16.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'bucketList/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'bucketList/favicon-96x96.png' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'bucketList/bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'bucketList/styles.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="{% static 'bucketList/multi-select.css'%}" media="screen" rel="stylesheet" type="text/css">
  <script src="{% static 'bucketList/scripts/googleImagesSearch.js' %}" type="text/javascript"></script>
  <style >
    body {
      background-image: url('{% static 'bucketList/images' %}/{% block bg %}{% endblock %}');
    }
  </style>
</head>

<body>
  {% include "tripIdeas/navbar.html" %}
  {% block content %}
  {% endblock %}
</body>

</html>

BucketListServer/tripIdeas/templates/tripIdeas/by_filter.html
{% extends 'tripIdeas/base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Trip Ideas - Par pays{% endblock %}

{% block content %}

<script>
function showDiv(id) {
  var elem = document.getElementById(id);
  if (elem.style.display == "none") {
    document.getElementById(id).style.display = "block";
  } else {
    document.getElementById(id).style.display = "none";
  }
}
</script>

  <div class="jumbotron col-lg-10 offset-lg-1 see-through main-div">
    {% if ordered_activities %}
      {% for filter in ordered_activities %}
        <div class="card border-info mb-3">
          <div class="card-header">
            <a class="text-info category-card-title" onclick="showDiv('{{filter.filter}}')">{{filter.filter}}</a>
          </div>
          <div class="card-body" id="{{filter.filter}}" style="display:none;">
            <ul>
              {% for activity in filter.activities %}
                <li><a class="text-info" href="/tripIdeas/activity/{{activity.pk}}">{{activity.title}}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
      {% endfor %}
    {% endif %}
  </div>

{% endblock %}

BucketListServer/tripIdeas/templates/tripIdeas/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation" style="">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse more-left-margin" id="navbarColor02">
    <div class="dropdown">
      <a class="dropbtn navbar-brand no-margin-right small-padding-sides" href="{% url 'tripIdeas:index' %}">Trip Ideas</button>
        <div class="dropdown-content">
          <a class="navbar-brand no-margin-right" href="{% url 'bucketList:index' %}">BucketList</a>
        </div>
    </div>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <div class="dropdown">
        <a class="dropbtn nav-link">Activité <span class="glyphicon glyphicon-collapse-down"></span></button>
        <div class="dropdown-content">
          <a class="nav-link" href="{% url 'tripIdeas:by_country' %}">Par pays</a>
          <a class="nav-link" href="{% url 'tripIdeas:by_season' %}">Par Saison</a>
          <a class="nav-link" href="{% url 'tripIdeas:last_changes' %}">Derniers ajouts/modifications</a>
          <a class="nav-link add-dropdown-item" href="{% url 'tripIdeas:new_activity' %}">Nouveau</a>
        </div>
      </div>
      </li>
      <li class="nav-item">
        <div class="dropdown">
        <a class="dropbtn nav-link">Voyages <span class="glyphicon glyphicon-collapse-down"></span></button>
        <div class="dropdown-content">
          <a class="nav-link" href="{% url 'tripIdeas:all_trips' %}">Toutes les voyages</a>
          <a class="nav-link" href="{% url 'tripIdeas:last_changes_trip' %}">Derniers ajouts/modifications</a>
          <a class="nav-link add-dropdown-item" href="{% url 'tripIdeas:new_trip' %}">Nouveau</a>
        </div>
      </div>
      </li>
      <li class="nav-item">
        <div class="dropdown">
        <a class="dropbtn nav-link">APIs <span class="glyphicon glyphicon-collapse-down"></span></button>
        <div class="dropdown-content">
          <a class="nav-link" href="{% url 'tripIdeas:working_on_it' %}">Price/Cost API (!)</a>
          <a class="nav-link" href="{% url 'tripIdeas:working_on_it' %}">Sleep API (!)</a>
          <a class="nav-link" href="{% url 'tripIdeas:working_on_it' %}">Localisation API (!)</a>
        </div>
      </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'tripIdeas:search_item' %}" method="post">
      {% csrf_token %}
      <input class="form-control mr-sm-1" type="text" placeholder="Search" name="search_value" id="search_value" autocomplete="off">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit"><span class="glyphicon glyphicon-search"></span></button>
    </form>
  </div>
</nav>

BucketListServer/tripIdeas/templates/tripIdeas/trip_detail.html
{% extends 'tripIdeas/base_layout.html' %}

{% block bg %}{{bg}}{% endblock %}

{% block title %}Trip Ideas - Détails voyage{% endblock %}

{% block content %}

<script src="/admin/jsi18n"></script>

<div class="jumbotron see-through card border-primary col-lg-10 trip_center_div">
  {% if trip %}
    <h2 style="margin-bottom: 30px; text-decoration: underline;">{{trip.title}}</h2>
    <h5>Description:</h5><p>{{trip.description}}</p>

    <div class="form-group">
      <div class="card border-primary">
        <h5>Pays:</h5>
        <ul class="country-list">
          {% for country in trip.country_list %}
            <li>{{country.name}}<img class="flag-icon" src="{{country.flag}}"/></li>
          {% empty %}
            <li>Aucun(e) pays/activité</li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <h5>Date de création: {{trip.created_date_time}}</h5>
    <h5>Date de modification: {{trip.modified_date_time}}</h5>
    <h5>Créateur: {{trip.get_creator_display}}</h5>
    <div class="row">
      <a href="{% url 'tripIdeas:trip_edit' pk=trip.pk %}" style="margin-top: 30px; width: 200px; margin-right: 10px; display: inline-block;" class="btn btn-outline-warning">Éditer</a>
      <a href="{% url 'tripIdeas:trip_delete' pk=trip.pk %}"" style="margin-top: 30px; margin-left: 10px; width: 200px; display: inline-block;" class="btn btn-outline-danger">Supprimer</a>
    </div>
  {% endif %}
</div>

{% endblock %}